server.port=8080

spring.application.name=API-GATEWAY

# Enable service discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# =========================
# GATEWAY ROUTES (UPDATED)
# =========================

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# Taskk Service
spring.cloud.gateway.server.webflux.routes[1].id=taskk-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://TASKK-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/tasks/**

#Logging configuration- 
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] [%thread] %-5level %logger{36} - %msg%n

# JWT
jwt.secret=c2VjdXJlS2V5VGhhdFNob3VsZEFiZVNldmVyQnl0ZXM=
jwt.access.expiration=3600000
jwt.refresh.expiration=86400000